### ISSUE TITLE
`autospec-web` should somehow allow to error out when curling for the error messages.

### ISSUE THREAD

**Issue by soenkehahn** [hspec/autospec#8]
It should be possible to query `autospec-web` while getting a non-zero exit code for failures.

The naive `curl localhost:8080` does not work since `curl` always returns `0` when the server responds. My next try was `curl --fail localhost:8080`, which should translate non-200 http status codes to exit code `22`. But that doesn't help since `autospec-web` always returns 200.

**Comment by sol** [comment]
Yes, if there is a sensible HTTP status code for this then that would be a nice way to do it.

**Comment by soenkehahn** [comment]
Maybe `412 Precondition Failed`. Seems the most appropriate to me.

**Comment by sol** [comment]
Yes, sounds good :)
